### ISSUE TITLE
Update on demand

### ISSUE THREAD

**Issue by simonster** [mronkko/ZotPad#21]
Right now, it seems like the only way to force ZotPad to update is to close it in the app switcher and open it again. Manual updating could be implemented similarly to Facebook (scrolling up past the top of a list reveals a "Release to update..." message).

**Comment by mronkko** [comment]
I need some more details on this one. ZotPad 1.0 should update the data as follows:
1 ) Library and collection hierarchy is updated when the app is started
2 ) Item-collection relationships are updated for all collections when a library is selected on the library list.
3 ) Item-collection relationships are updated for for a collection when that collection is selected
4 ) Items are updated when a library is selected (ZotPad will only retrieve a subset of items that have changed)
5 ) Item and its children are updated when its details are viewed.

Do you think that one of these rules does not currently work, or do you think that the rules should be different?

I have been planning for a way to update the library-collection tree on the fly, but have not had time to do that yet.

**Comment by simonster** [comment]
I didn't test updating items. That works fine, and I think the current rules for automatically updating are fine, but it would be nice to be able to update the collection tree without force-closing the app. It might also be nice to be able to update the current collection without reselecting it, although this seems less important.

**Comment by mronkko** [comment]
I have been thinking about a solution to updating the collection tree. I though about loading a list of collections every time their parent is chosen. However, because the entire collection hierarchy can be retrieved with one API call, I decided to do that instead. I will most likely implement retrieving collections when their parent is chosen. This would still require a solution to updating the list of libraries, but this will be rare. I was thought about doing this in an in-app preference window instead of "pull to update". But in any case, this will be implemented after 1.1 release. 

You can force-update the items in a collection by reselecting the same collection.

**Comment by mronkko** [comment]
Collections are now updated on the fly
