### ISSUE TITLE
Beta confuses "My Library" and group library

### ISSUE THREAD

**Issue by simonster** [mronkko/ZotPad#42]
ZotPad beta doesn't "My Library" in its list view. Instead, it shows a library named CHNM (which is a group library I'm subscribed to) that contains the contents of my library (not the CHNM library). There doesn't seem to be a way to access the CHNM library.

There seems to be a potentially related issue with the ZotPad 1.0.2, although it's not quite as strange. While ZotPad 1.0.2 shows My Library in the list view and the contents are correct, it does not show the CHNM library at all.

**Comment by mronkko** [comment]
Does the CHNM group have group ID 1? If it does, this is caused by conflicting libraryID in ZotPad.

The way ZotPad works is that it tries to be agnostic to the library type as much as possible. Each library has a libraryID. My Library is 1 and all others are coded by the groupID. I did not use 0 for My Library because it can be confused with null, but worked with the assumption that if there is a group 1, it is probably a test group that no-one uses. 

Once you confirm the group ID, I will see what is the best way to solve this issue.

**Comment by simonster** [comment]
Yes, it has group ID 1. If this only affects me, I don't really care. (I don't think I'll ever need to access the CHNM group from my iPad.)

**Comment by mronkko** [comment]
Do you think that anyone else will want to access that library with ZotPad? 

I will probably fix this at some point, but most likely not for 1.1.

**Comment by simonster** [comment]
It's been a 18 months since anyone touched that library, so I doubt it's particularly important that it's accessible. However, if there's an easy way to correct the name in the collections view for my library, I'd appreciate it.

**Comment by mronkko** [comment]
You can disable that library for the API key that you are using. 

I will fix this some time in the future, but not for 1.1, because changing how my library is coded is likely to introduce bugs in the code and I want to make a release.
